// components/Page/Contact.tsx
import { css } from "@emotion/react";
import styled from "@emotion/styled";
import { Icon } from "@iconify-icon/react";
import { FunctionComponent } from "react";
import { ui } from "../../styles/prism";
import CardDeck from "../CardDeck";
import { ContactItem } from "../_shared";

const Contact: FunctionComponent = () => {
  return (
    <article css={style.Contact}>
      <div css={style.IconTitle}>
        <Icon
          icon="fluent-emoji-flat:call-me-hand-light"
          width={40}
          height={40}
        />
        <div>
          <h3>contact</h3>
          <p>want a talk? reach out.</p>
        </div>
      </div>

      <CardDeck columns={2}>
        <ContactItem
          {...{
            icon: "tabler:brand-twitter",
            link: "https://twitter.com/dorkodu",
            type: "twitter",
            address: "@dorkodu",
            description: "(news)",
          }}
        />
        <ContactItem
          {...{
            icon: "tabler:brand-github",
            link: "https://github.com/dorkodu",
            type: "github",
            address: "@dorkodu",
            description: "(open source)",
          }}
        />
        <ContactItem
          {...{
            icon: "tabler:brand-instagram",
            link: "https://instagram.com/d0rukeray",
            type: "instagram",
            address: "@dorkodu",
            description: "(social)",
          }}
        />
        <ContactItem
          {...{
            icon: "tabler:mail-opened",
            link: "mailto:hey@dorkodu.com",
            type: "email",
            address: "hey@dorkodu.com",
            description: "(formal)",
          }}
        />
      </CardDeck>
    </article>
  );
};

export default Contact;

const style = {
  Contact: css`
    display: flex;
    flex-direction: column;
    gap: 1rem;
    padding: 1rem 0;
  `,
  IconTitle: css`
    display: inline-flex;
    gap: 1rem;
    margin: 1rem auto;
    padding: 0 1rem;

    div {
      h3 {
        padding: 0;
        margin: 0;
        text-align: left;
      }

      p {
        padding: 0;
        margin: 0;
      }
    }
  `,
};

// components/Page/Contact.vue
<template>
  <article>
    <h3 style="margin-bottom: .5rem;">
      <Icon name="fluent-emoji-flat:call-me-hand-light" size="36" />
      contact
    </h3>
    <p style="margin: 0; margin-bottom: 1rem; text-align: center;">wanna reach out? wave a hand!</p>
    <CardDeck :columns="2">
      <div class="IconItem">
        <Icon name="tabler:brand-twitter" />
        <div>
          <span><a href="https://twitter.com/dorkodu">twitter</a></span>
          <span><b>@dorkodu</b><br>(news)</span>
        </div>
      </div>
      <div class="IconItem">
        <Icon name="tabler:brand-github" />
        <div>
          <span><a href="https://github.com/dorkodu">github</a></span>
          <span><b>@dorkodu</b><br>(open source)</span>
        </div>
      </div>
      <div class="IconItem">
        <Icon name="tabler:brand-instagram" />
        <div>
          <span><a href="https://instagram.com/d0rukeray">instagram</a></span>
          <span><b>@dorkodu</b><br>(social)</span>
        </div>
      </div>
      <div class="IconItem">
        <Icon name="tabler:mail-opened" />
        <div>
          <span><a href="mailto:doruk@dorkodu.com">email</a></span>
          <span><b>hey@dorkodu.com</b><br>(officials)</span>
        </div>
      </div>
    </CardDeck>
  </article>
</template>
<script setup lang="ts">

</script>
<style lang="scss" scoped>

</style>
