// components/DescriptiveItem.vue
<template>
  <div class="descriptive-item">
    <span class="__badge">
      <slot></slot>
    </span>
    <div class=".__contents">
      <dt>{{ title }}</dt>
      <dd>{{ description }}</dd>
    </div>
  </div>
</template>

<script setup lang="ts">
const { title, description } = defineProps<{
  title: string;
  description: string;
}>();
</script>

<style lang="scss" scoped>
@import "styles";

.descriptive-item {
  display: flex;
  flex-direction: row;
  gap: 1rem;

  .__badge {
    display: inline-block !important;
  }

  dt {
    font-weight: 700;
    font-size: 1.25rem !important;
    line-height: 1.5rem;
    color: $reference-color-gray-10;

    .--bulletpoint {
      color: $reference-color-gray-70;
    }
  }

  dd {
    color: $reference-color-gray-20;
    font-weight: 400;
    padding-top: .25rem;
    line-height: 1.25;
    font-size: 1.15rem;
  }
}
</style>

// next/components/DescriptiveItem.tsx
import styled from "@emotion/styled";
import { FunctionComponent } from "react";
import { tokens } from "../styles/prism";

interface DescriptiveItemProps {
  title: string;
  description: string;
  badge?: React.ReactNode;
  children?: React.ReactNode;
}

const DescriptiveItem: FunctionComponent<DescriptiveItemProps> = ({
  title,
  description,
  badge,
  children,
}) => {
  return (
    <DItem>
      {badge && <Badge>{badge}</Badge>}
      <dt>{title}</dt>
      <dd>{description}</dd>
      {children}
    </DItem>
  );
};

export default DescriptiveItem;

const Badge = styled.div`
  display: inline-block !important;
`;

const DItem = styled.div`
  display: flex;
  flex-direction: row;
  gap: 1rem;

  dt {
    font-weight: 700;
    font-size: 1.25rem !important;
    line-height: 1.5rem;
    color: ${tokens.color.gray(10)};

    .--bulletpoint {
      color: ${tokens.color.gray(70)};
    }
  }

  dd {
    color: ${tokens.color.gray(20)};
    font-weight: 400;
    padding-top: 0.25rem;
    line-height: 1.25;
    font-size: 1.15rem;
  }
`;
