// pages/index.vue
<script lang="ts" setup>
const hero = {
  title: "we are dorkodu.",
  tagline: "the meaningful technology company.",
  statement: `we liberate the human. this is our mission.`,
  picture: {
    source: "/images/doruk--green.png",
    title: "pixelated, natively digital 💽"
  },
};

definePageMeta({
  title: "welcome!",
  description: `liberate the human!`,
  keywords: `dorkodu, dorkodu.com, dorkodia, liberate, gamification, productivity, humane technology`,
});
</script> 

<template>
  <main>
    <Showcase style="margin-top: 0;">
      <template #main>
        <Hero :title="hero.title" :tagline="hero.tagline" :statement="hero.statement" style="margin-top: 0 !important;">
          <template #head>
            <Icon name="twemoji:leaf-fluttering-in-wind" size="48" />
          </template>
          <template #content>
            <p class="hashtag">#gamification #web3 #knowledge #artworks</p>
            <div class="button-container">
              <Button type="fill" link="/story">our story</Button>
              <Button type="tonal" link="/work">join us!</Button>
            </div>
          </template>
        </Hero>
      </template>
      <template #side>
        <Picture :source="hero.picture.source" :title="hero.picture.title" />
      </template>
    </Showcase>

    <Break />

    <article>
      <h2>
        <Icon name="fluent-emoji-flat:thinking-face" size="32" />&nbsp;
        <span>who we are?</span>
      </h2>

      <p style="font-size: 1.25rem; margin: 0;">
        <span class="paragraph-tagline">what we do;</span>
        <br>
        <br>find their unique spark & actualize themselves
        <br>build the utopian dream of heaven on earth;
        <br>create a free and happy life experience, for everyone;
        <br><b>liberate the human with meaningful technology.</b>
      </p>
      <p>— yep. this is why i wake up every day.</p>
      <SectionRuler />
    </article>

    <article>
      <h2>
        <span>hello, again.</span>&nbsp;
        <Icon name="fluent-emoji-flat:waving-hand-light" size="36" />
      </h2>
      <Bulletpoint icon="twemoji:leaf-fluttering-in-wind">
        <p style="font-size: 1.25rem; margin: 0; font-weight: 400;">
          <span class="paragraph-tagline">our purpose;</span>
          <br><b>liberate the humankind.</b>
        </p>
      </Bulletpoint>
      <Bulletpoint icon="twemoji:bullseye">
        <p style="font-size: 1.25rem; margin: 0; font-weight: 400;">
          <span class="paragraph-tagline">my mission;</span>
          <br>
          we combine gamification, human-centric design with our superior technology
          and create products that help people...
          <br>create a free and happy life experience for everyone,
          <br>build the utopian dream of heaven on earth,
          <br><b>...with our meaningful products & technology.</b>
        </p>
      </Bulletpoint>
      <SectionRuler />
    </article>



    <PageContact />

    <Break />

    <PageLegend />

    <Break />
  </main>
</template>
<style lang="scss">
@import "styles";
</style>

// dorkodu.com/src/pages/index.tsx
import Head from "next/head";

import {
  Container,
  Grid,
  SimpleGrid,
  Skeleton,
  rem,
  useMantineTheme,
  Card,
  Title,
  Text,
  Box,
  Paper,
  Group,
  createStyles,
  Button,
  ThemeIcon,
  Col,
  Stack,
  List,
  Image,
  CSSObject,
} from "@mantine/core";

import { IconReceiptOff, IconFlame, IconCircleDotted, IconFileCode } from "@tabler/icons-react";

import WebsiteLayout from "@/layouts/WebsiteLayout";
import { NextPage } from "next";

import Meta from "@/components/Meta";
import { HeroIndex } from "@/components/Hero/HeroIndex";
import { EmailBanner } from "@/components/Newsletter";

import ForumIcon from "@/assets/logos/forum_Icon.svg";
import IDIcon from "@/assets/logos/id_Icon.svg";

import { ProductShowcaseGrid } from "@/components/Product";
import { FeaturedUseCases } from "@/components/Features";
import { FAQs } from "@/components/FAQ";
import { HeroWithBackground } from "@/components/Hero/HeroWithBackground";
import { FeaturedUsecases } from "@/data/featured";
import Dorkodu from "@/types/dorkodu";
import { projects } from "@/data/products";
import { SectionTitle } from "@/components/Commons";
import { Bullseye, Leaf } from "@/styles/twemoji";

const meta = {
  title: "welcome! — dorkodu",
  description: `liberate the humankind.`,
  keywords: `dorkodu, dorkodu.com, dorkodia, liberate, gamification, productivity, humane technology`,
  url: "/",
  image: {
    src: "/public/images/dorkodu-single.png",
    alt: "dorkodu logo with single letter.",
  },
};

const Home: NextPage = () => {
  return (
    <WebsiteLayout>
      <Head>
        <Meta {...meta} />
      </Head>
      <HeroIndex />
      <Products />
      <Punchline />
      <FeaturedUseCases {...FeaturedUsecases} />
      <ProsConsList />
      <Mission />
      <FAQs />
      <LeadGrid />
      <Newsletter />
    </WebsiteLayout>
  );
};

const Products = () => {
  const products: Dorkodu.Project[] = [
    { title: "Forum", tagline: "Social Discourse", image: ForumIcon.src, link: "/products/forum" },
    { title: "ID", tagline: "Your Digital Identity", image: IDIcon.src, link: "/products/id" },
  ];

  return (
    <Box my={60}>
      <Title order={2} weight={800}>
        Our Apps
      </Title>
      <ProductShowcaseGrid products={products} />
    </Box>
  );
};

const ProsConsList = () => {
  return <></>;
};

const Punchline = () => {
  return <></>;
};

const Newsletter = () => {
  return <EmailBanner />;
};

export const Mission = () => {
  return (
    <Container my={25}>
      <Title order={2}>Who We Are?</Title>

      <Box component="section" id="our-purpose" py={20}>
        <SectionTitle title="Our Purpose" text="Why we do this?" icon={Leaf} />
        <List>
          <List.Item>find their true purpose & passion.</List.Item>
          <List.Item>actualize themselves.</List.Item>
          <List.Item>create a free and happy life experience for everyone.</List.Item>
          <List.Item>build the utopian dream of heaven on earth.</List.Item>
        </List>
      </Box>

      <Box component="section" id="people" py={20}>
        <SectionTitle title="Our Mission" text="Our roadmap and objectives." icon={Bullseye} />
        <List>
          <List.Item>find their true purpose & passion.</List.Item>
          <List.Item>actualize themselves.</List.Item>
          <List.Item>create a free and happy life experience for everyone.</List.Item>
          <List.Item>build the utopian dream of heaven on earth.</List.Item>
        </List>
      </Box>

      <Stack>
        <Title>Our Mission</Title>
        <Text>
          we combine <em>gamification</em>, <em>human-centric design</em> and <em>our superior technology</em> to create
          products which <em>free the human spirit.</em>
        </Text>
      </Stack>
    </Container>
  );
};

export const OurWork = () => {
  return (
    <div>
      {projects.map((project, index) => (
        <div key={index}>
          <img src={project.image} alt={project.title} />
          <h4>{project.title}</h4>
          <p>{project.tagline}</p>
          <p>
            <span>{project.type}</span>
          </p>
        </div>
      ))}
    </div>
  );
};

const LeadGrid = () => {
  const theme = useMantineTheme();
  const PRIMARY_COL_HEIGHT = rem(300);
  const SECONDARY_COL_HEIGHT = `calc(${PRIMARY_COL_HEIGHT} / 2 - ${theme.spacing.md} / 2)`;

  return (
    <Container my="md">
      <SimpleGrid cols={2} spacing="md" breakpoints={[{ maxWidth: "sm", cols: 1 }]}>
        <Skeleton height={PRIMARY_COL_HEIGHT} radius="md" animate={false} />
        <Grid gutter="md">
          <Grid.Col>
            <Skeleton height={SECONDARY_COL_HEIGHT} bg="blue" radius="md" animate={false} />
          </Grid.Col>
          <Grid.Col span={6}>
            <Skeleton height={SECONDARY_COL_HEIGHT} bg="blue" radius="md" animate={false} />
          </Grid.Col>
          <Grid.Col span={6}>
            <Skeleton height={SECONDARY_COL_HEIGHT} bg="blue" radius="md" animate={false} />
          </Grid.Col>
        </Grid>
      </SimpleGrid>
    </Container>
  );
};

export default Home;
