// pages/business.vue
<script lang="ts" setup>

definePageMeta({
  title: "welcome!",
  description: `liberate the humankind.`,
  keywords: `dorkodu, dorkodu.com, dorkodia, liberate, gamification, productivity, humane technology`,
});

</script> 
  
<template>
  <main>
    <Showcase style="margin-top: 0;">
      <template #main>
        <Hero :data="{
          title: `our business`,
          tagline: `company insights for investors, sponsors and our community.`,
          statement: `dorkodu is not a conventional company. we do not intend to be one. Staying humble and focusing on creating
          value is our only ambition.`
        }" style="margin-top: 0 !important;">
        </Hero>
      </template>
      <template #side>
        <Picture source="/images/undraw_dorkodu-work-culture.png" />
      </template>
    </Showcase>

    <Break />

    <Hero :data="{
      title: `hello`,
      tagline: `hello`,
      statement: `hello`
    }" center>
      <template #head></template>
      <template #content></template>
    </Hero>

    <Showcase>
      <template #main>
        <DescriptiveList icon="tabler:building" title="company overview" message="">

          <DescriptiveItem title="our name"
            description="our founder doruk eray wanted to create a unique word for easily getting a .com domain. so our name ended up being 'dorkodu', doruk + code.">
            <Icon name="twemoji:fire" size="32" />
          </DescriptiveItem>

          <DescriptiveItem title="technology"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, aspernatur.">
            <Icon name="twemoji:fire" size="32" />
          </DescriptiveItem>

          <DescriptiveItem title="business"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, aspernatur.">
            <Icon name="twemoji:fire" size="32" />
          </DescriptiveItem>

          <DescriptiveItem title="culture"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, aspernatur.">
            <Icon name="twemoji:fire" size="32" />
          </DescriptiveItem>

          <DescriptiveItem title="management"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, aspernatur.">
            <Icon name="twemoji:fire" size="32" />
          </DescriptiveItem>

          <DescriptiveItem title="goals" description="we want dorkodu to be the best gamification">
            <Icon name="twemoji:fire" size="32" />
          </DescriptiveItem>

        </DescriptiveList>
      </template>
      <template #side>

      </template>
    </Showcase>

    <section>
      <h2>
        <span>hello, again.</span>&nbsp;
        <Icon name="fluent-emoji-flat:waving-hand-light" size="36" />
      </h2>
      <Bulletpoint icon="twemoji:leaf-fluttering-in-wind">
        <p style="font-size: 1.25rem; margin: 0; font-weight: 400;">
          <span class="paragraph-tagline">our purpose</span>
          <br><b>liberate the humankind.</b>
        </p>
      </Bulletpoint>
      <Bulletpoint icon="twemoji:bullseye">
        <p style="font-size: 1.25rem; margin: 0; font-weight: 400;">
          <span class="paragraph-tagline">our mission</span>
          <br>
          we combine gamification, human-centric design with our superior technology
          and create products that help people...
          <br>create a free and happy life experience for everyone,
          <br>build the utopian dream of heaven on earth,
          <br><b>...with our meaningful products & technology.</b>
        </p>
      </Bulletpoint>
      <SectionRuler />
    </section>

    <section>
      <h2>our people</h2>
      <TeamMember name="doruk eray" title="founder & chief"
        about="cult leader, product polymath, creative psychedelic, progressive craftsman, lunatic. software, ui/ux, artwork, business."
        avatar="/images/doruk--green.png">
        <template #icons>
          <Icon name="tabler:flag-3" size="32" />
          <Icon name="tabler:tools" size="32" />
          <Icon name="tabler:building-bank" size="32" />
        </template>
        <template #more></template>
      </TeamMember>
      <hr>
      <TeamMember name="berk cambaz" title="technologist"
        about="Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus, enim. Dolorem doloremque similique dolorum repellat minus sequi fugiat nihil?"
        avatar="/images/berk.png">
        <template #icons>
          <Icon name="tabler:brand-open-source" size="32" />
          <Icon name="tabler:cpu" size="32" />
          <Icon name="tabler:code" size="32" />
        </template>
        <template #more></template>
      </TeamMember>
    </section>

    <PageContact />

    <Break />

    <PageLegend />

    <Break />
  </main>
</template>
<style lang="scss">
@import "styles";
</style>

// pages/business.tsx
import { css } from "@emotion/react";
import type { NextPage } from "next";
import Image from "next/image";
import Button from "../components/Button";
import Hero from "../components/Hero";
import Polaroid from "../components/Polaroid";
import { ButtonContainer, Showcase, IconTitle } from "../styles/blame";
import { tokens, ui } from "../styles/prism";
import Page from "../components/Page";
import Bulletpoint from "../components/Bulletpoint";
import { ParagraphTagline } from "../styles/blame";
import { Icon } from "@iconify-icon/react";
import DescriptiveList from "../components/DescriptiveList";
import DescriptiveItem from "../components/DescriptiveItem";
import Quote from "../components/Quote";

import Testimonial from "../components/Testimonial";

// images
import IntroIllustration from "../public/images/undraw_dorkodu-work-culture.png";

const meta = {
  title: "business — dorkodu",
  description: `join the revolution!`,
  keywords: `work @ dorkodu, careers at dorkodu, careers dorkodu, dorkodu jobs, work at dorkodu`,
  url: "/",
  image: {
    src: "/public/images/dorkodu-single.png",
    alt: "dorkodu logo with single letter.",
  },
};

const image = {
  intro: IntroIllustration,
};

const style = {
  hashtag: css`
    color: ${tokens.color.blue(48)};
    font-size: 1.15rem;
    font-weight: 500;
    padding: 0;
    margin: 0 !important;
  `,
  arrowList: css`
    position: relative;
    list-style: none;
    margin: 0 !important;
    padding-left: 1.5em;
    font-size: 1.25rem;

    li:before {
      content: "⇢";
      position: absolute;
      left: 0;
      font-weight: 600;
      font-size: 1.5rem;
      line-height: 1.5rem;
      color: ${tokens.color.gray(75)};
    }
  `,
  p: {
    mission: css`
      font-size: 1.25rem;
      margin: 0;
      font-weight: 400;
    `,
  },
};

const Business: NextPage = () => {
  return (
    <>
      <Page.Meta {...meta} />

      <Showcase>
        <Hero
          {...{
            title: `our business`,
            tagline: `company insights for investors, sponsors and our community.`,
            statement: `dorkodu is not a conventional company. we do not intend to be one. staying humble and focusing on creating
          value is our only ambition.`,
          }}
        >
          <p css={style.hashtag}>
            #software #ui/ux #graphics
            <br />
            #design #economics #knowledge
          </p>
          <ButtonContainer>
            <Button type="fill" link="#story">
              continue
            </Button>
            <Button type="tonal" link="/business">
              be an investor<i>!</i>
            </Button>
          </ButtonContainer>
        </Hero>
        <Polaroid source={image.intro} />
      </Showcase>

      <Showcase>
        <Page.Index
          items={[
            ["#lorem", "lorem"],
            ["#lorem", "lorem ipsum"],
            ["#lorem", "about us"],
            ["#lorem", "open roles"],
            ["#lorem", "some boring stuff"],
          ]}
        />
        <article>
          <h2>opportunities at dorkodu</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi
            illo sapiente odio nesciunt magnam iure eaque, nemo, blanditiis rem
            impedit placeat optio? Nulla, sequi labore!
          </p>
        </article>
      </Showcase>

      <Introduction />
      <Mission />
      <Story />
      <Values />
      <CorporateOverview />
      <Press />

      <section>
        <Testimonial
          {...{
            quote: `
            i founded dorkodu because i believed
            we can create a technology company with human-centric values;
            this was my dream at first;
            then became dorkodu's purpose.`,
            name: "doruk eray",
            title: "founder & chief",
          }}
        />
      </section>
    </>
  );
};

export default Business;

//?::: PAGE SECTIONS :::?//

const Introduction = () => {
  const local = {};
  return <></>;
};

const Mission = () => {
  const local = {};
  return <></>;
};

const Story = () => {
  const local = {};
  return <></>;
};

const Values = () => {
  const local = {};
  return <></>;
};

const CorporateOverview = () => {
  const local = {};
  return <></>;
};

const Press = () => {
  const local = {};

  return (
    <>
      <div css={IconTitle}>
        <Icon icon="twemoji:rolled-up-newspaper" width={40} height={40} />
        <div>
          <h2>press</h2>
          <p></p>
        </div>
      </div>
      <Page.Contact />
    </>
  );
};
